name: FGO Version Code Extraction - JP

on:
  push:
    branches: ["JP"]
  pull_request:
    branches: ["JP"]
  schedule:
    - cron: "15 04 * * *"
    - cron: "15 16 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Parse APK
        run: python main.py

      - name: Commit Changes
        uses: actions-js/push@master
        with:
          force: true
          branch: "JP"
          github_token: ${{ secrets.TOKEN_REPO }}