name: Fate Grand Order VerCode Extraction

on:
  workflow_dispatch:
  schedule:
    - cron: "05 04 * * *"
    - cron: "05 09 * * *"
  push:
    branches:
      - NA
      - JP
  pull_request:
    branches:
      - NA
      - JP

jobs:
  build-NA:
    runs-on: windows-latest

    steps:
      - name: Checkout NA branch
        uses: actions/checkout@v4
        with:
          ref: NA

      - name: Set up Python for NA
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Requirements for NA
        run: |
          pip install --cache-dir ~/.pip-cache -r requirements.txt --user

      - name: Execute NA script
        run: python main.py

      - name: Commit & push changes to NA branch
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Automated commit for NA branch"
          git push origin NA
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_REPO }}

  build-JP:
    runs-on: windows-latest

    steps:
      - name: Checkout JP branch
        uses: actions/checkout@v4
        with:
          ref: JP

      - name: Create pip cache directory if none exists
        run: |
          mkdir -p ~/.pip-cache

      - name: Set up Python for JP
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Requirements for JP
        run: |
          pip install --cache-dir ~/.pip-cache -r requirements.txt --user

      - name: Execute main script for JP
        run: python main.py

      - name: Commit & push changes to JP branch
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Automated commit for JP branch"
          git push origin JP
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_REPO }}
