name: Code Extraction Workflow

on:
  schedule:
    - cron: "0 7,19 * * *"  # Run at 7:00 and 19:00
  push:
    branches:
      - JP
      - NA
  pull_request:
    branches:
      - JP
      - NA
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest  # Use the Windows environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: ~/.pip-cache
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11  # Specify your desired Python version

      - name: Install Requirements
        run: |
          pip install --cache-dir ~/.pip-cache -r requirements.txt

      - name: Execute main script
        run: |
          python main.py

      - name: Commit & push changes to branch
        if: startsWith(github.ref, 'refs/heads/${{ github.event.inputs.branch }}')
        uses: actions-js/push@master
        with:
          force: true
          branch: ${{ github.ref }}
          github_token: ${{ secrets.TOKEN_REPO }}