name: Code Extraction Workflow

on:
  schedule:
    - cron: "0 07 * * *"
    - cron: "0 19 * * *"
  push:
    branches:
      - JP
  pull_request:
    branches:
      - JP
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest  # Use the Windows environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: JP

      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: ~/.pip-cache
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Requirements
        run: |
          pip install --cache-dir ~/.pip-cache -r requirements.txt

      - name: Execute main script
        run: |
          python main.py

      - name: Commit & push changes to branch
        uses: actions-js/push@master
        with:
          force: true
          branch: JP
          github_token: ${{ secrets.TOKEN_REPO }}