name: Extracting VerCode - NA

on:
  schedule:
    - cron: "1 4 * * *"
    - cron: "1 8 * * *"
    - cron: "1 9 * * *"
    - cron: "1 16 * * *"
  push:
    branches: ["NA"]
  pull_request:
    branches: ["NA"]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Requirements
        run: |
          pip install -r requirements.txt

      - name: Execute main script
        run: python main.py

      - name: Commit & push changes to branch NA
        uses: actions-js/push@master
        with:
          force: true
          branch: "NA"
          github_token: ${{ secrets.TOKEN_REPO }}