name: Code Extraction Workflow for NA Branch

on:
  schedule:
    - cron: "0 */1 * * *"  # Run every hour
  push:
    branches:
      - NA
  pull_request:
    branches:
      - NA

jobs:
  build:
    runs-on: windows-latest  # Switch back to Windows environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@latest
        with:
          ref: NA

      - name: Cache Python dependencies
        uses: actions/cache@latest
        with:
          path: ~/.pip-cache
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt', 'Pipfile.lock', 'pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@latest
        with:
          python-version: 3.11  # Specify your desired Python version

      - name: Install Requirements
        run: |
          pip install -r requirements.txt

      - name: Execute main script
        run: python main.py

      - name: Commit & push changes to branch JP
        uses: actions-js/push@master
        with:
          force: true
          branch: "NA"
          github_token: ${{ secrets.TOKEN_REPO }}