name: Code Extraction Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: "05 04 * * *"
    - cron: "05 09 * * *"
  push:
    branches:
      - NA
      - JP
  pull_request:
    branches:
      - NA
      - JP

jobs:
  build-NA:
    runs-on: windows-latest  # Use the Windows environment

    steps:
      - name: Checkout NA branch
        uses: actions/checkout@v4
        with:
          ref: NA

      - name: Cache Python dependencies for NA
        uses: actions/cache@v4
        with:
          path: ~/.pip-cache
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python for NA
        uses: actions/setup-python@v5
        with:
          python-version: 3.11  # Specify your desired Python version
          cache: "pip"
          
      - name: Install Requirements for NA
        run: |
          pip install --cache-dir ~/.pip-cache -r requirements.txt

      - name: Execute main script for NA
        run: python main.py

      - name: Commit & push changes to NA branch
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Automated commit for NA branch"
          git push origin NA
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_REPO }}

  build-JP:
    runs-on: windows-latest  # Use the Windows environment

    steps:
      - name: Checkout JP branch
        uses: actions/checkout@v4
        with:
          ref: JP

      - name: Cache Python dependencies for JP
        uses: actions/cache@v4
        with:
          path: ~/.pip-cache
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python for JP
        uses: actions/setup-python@v5
        with:
          python-version: 3.11  # Specify your desired Python version
          cache: "pip"
          
      - name: Install Requirements for JP
        run: |
          pip install --cache-dir ~/.pip-cache -r requirements.txt

      - name: Execute main script for JP
        run: python main.py

      - name: Commit & push changes to JP branch
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Automated commit for JP branch"
          git push origin JP
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_REPO }}
