name: Code Extraction Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */1 * * *"  # Run every hour
  push:
    branches:
      - JP
      - NA
  pull_request:
    branches:
      - JP
      - NA

jobs:
  build:
    runs-on: windows-latest  # Use the Windows environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Cache Python dependencies
        uses: actions/cache@master
        with:
          path: ~/.pip-cache
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt', 'Pipfile.lock', 'pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.11  # Specify your desired Python version

      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute main script
        run: |
          if [[ ${{ github.ref }} == "refs/heads/JP" ]]; then
            python main.py --vercode JP
          elif [[ ${{ github.ref }} == "refs/heads/NA" ]]; then
            python main.py --vercode NA
          else
            echo "Unsupported branch: ${{ github.ref }}"
            exit 1
          fi

      - name: Commit & push changes to branch
        if: github.ref == 'refs/heads/${{ github.event.inputs.branch }}'
        uses: actions-js/push@master
        with:
          force: true
          branch: ${{ github.ref }}
          github_token: ${{ secrets.TOKEN_REPO }}
